# Instalar las gemas
gem install rest-client

#Importar las bibliotecas
require 'rest-client'
require 'json'

#Para crear la API
# el "--api" es el argumento que indica que ruby va a trabajar con una API
rails new APIFrancy --api

#se ejecuta

#Se ingresa a la carpeta
cd APIFrancy

#Se ingresa al servidor
rails server

#Scaffolds (no entendí bien esta parte)
#rakedb: Leer sobre esto

#Usar el jbuilder para la API




  

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
